apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-xkl980
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-xkl980
  namespace: my-nginx-xkl980
  labels:
    name: nginx-xkl980
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-xkl980
  template:
    metadata:
      namespace: my-nginx-xkl980
      labels:
        name: nginx-xkl980
    spec:
      containers:
      - name: nginx-xkl980
        image: nginx
        ports:
        - containerPort: 80

